### ISSUE TITLE
Installation problem : no module-info.java found

### ISSUE THREAD

**Issue by snehashis-roy** [glencoesoftware/NGFF-Converter#40]
Hello.
I am fairly new to java. I want to convert some nd2 files to tiff or ometiff using this software. I tried to install it using "./gradlew clean build" command. Here is the error output.
```
> Configure project :
Project : => no module-info.java found

> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> error: invalid source release: 16

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
2 actionable tasks: 1 executed, 1 up-to-date
```
My java version is this,
```
java -version
openjdk version "11.0.17" 2022-10-18 LTS
OpenJDK Runtime Environment (Red_Hat-11.0.17.0.8-2.el7_9) (build 11.0.17+8-LTS)
OpenJDK 64-Bit Server VM (Red_Hat-11.0.17.0.8-2.el7_9) (build 11.0.17+8-LTS, mixed mode, sharing)
```
Please let me know how to fix this.
Thank you.

**Comment by sbesson** [comment]
Hi @snehashis-roy, as indicated by https://github.com/glencoesoftware/NGFF-Converter/blob/b3a8b104d63b761f522640ade554e29f3801582b/build.gradle#L33, this application is expected to be compiled using JDK 16+ with JDK 17 LTS being the recommendation.

**Comment by DavidStirling** [comment]
You can also download prebuilt executables from [here](https://www.glencoesoftware.com/products/ngff-converter/).

**Comment by Pablo1990** [comment]
In Ubuntu 20.04, I installed openjdk-17 and it worked:

`sudo apt install openjdk-17-jdk`

I still got this warning though:

`> Configure project :
Project : => no module-info.java found
`

**Comment by sbesson** [comment]
@Pablo1990 could you paste the whole stack trace you are receiving?

**Comment by Pablo1990** [comment]
> @Pablo1990 could you paste the whole stack trace you are receiving?

Sorry, maybe I didn't explain correctly. I have the software working, but I'm just getting that warning, which I'm fine with :)

**Comment by sbesson** [comment]
Thanks @Pablo1990 and all understood. I'll close this as the original issue should be resolved by installing JDK 17.
Answering shortly https://github.com/glencoesoftware/NGFF-Converter/issues/40#issuecomment-1385561238, at the moment, the binaries are only built for Windows and OSX which are the main audiences for the GUI. For Linux artifacts, you will need to build yourseld
