### ISSUE TITLE
Can't open converted files

### ISSUE THREAD

**Issue by Pablo1990** [glencoesoftware/NGFF-Converter#49]
Hi,

I've used NGFF-Converter on Ubuntu 20.04 to transform some tif files into zarr. 

    Jun 14, 2023 10:58:58 AM com.sun.javafx.application.PlatformImpl startup
    WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @680dc59c'
    Jun 14, 2023 10:58:59 AM java.util.prefs.FileSystemPreferences$1 run
    INFO: Created user preferences directory.
    Jun 14, 2023 10:58:59 AM java.util.prefs.FileSystemPreferences$6 run
    WARNING: Prefs file removed in background /root/.java/.userPrefs/prefs.xml
    2023-06-14 10:59:30,013 [JavaFX Application Thread] INFO  com.glencoesoftware.convert.App - Beginning file conversion...
    
    2023-06-14 10:59:30,122 [Thread-4] INFO  c.g.convert.ConverterTask - Executing bioformats2raw with args [/media/pablo/d7c61090-024c-469a-930c-f5ada47fb049/PabloVicenteMunuera/3D_SegmentedDB/data/raw/WD1.1_17-03_WT_MP.tif, /media/pablo/d7c61090-024c-469a-930c-f5ada47fb049/PabloVicenteMunuera/3D_SegmentedDB/results/WD1.1_17-03_WT_MP.zarr, --log-level=WARN]
    2023-06-14 10:59:30,122 [JavaFX Application Thread] INFO  c.g.convert.ConverterTask - Working on WD1.1_17-03_WT_MP.tif
    OpenJDK 64-Bit Server VM warning: You have loaded library /tmp/opencv_openpnp4908659762648675157/nu/pattern/opencv/linux/x86_64/libopencv_java342.so which might have disabled stack guard. The VM will try to fix the stack guard now.
    It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
    2023-06-14 10:59:33,700 [Thread-4] INFO  c.g.convert.ConverterTask - Successfully created: WD1.1_17-03_WT_MP.zarr

The files are created. However, when I try to open them with Napari (having installed ome-zarr), I got this:

    ValueError: Plugin 'napari-ome-zarr' was selected to open ['/media/pablo/d7c61090-024c-469a-930c-f5ada47fb049/PabloVicenteMunuera/3D_SegmentedDB/results/WD1.1_17-03_WT_MP.zarr'], but returned no data.

I don't know if it is something related to the warnings that I am getting or if there is something else that I am missing...

Many thanks for your help!
Pablo

**Comment by sbesson** [comment]
@Pablo1990 this is likely related to the known issue that the `napari-ome-zarr` plugin does not support the layout generated by this conversion utility - see https://github.com/ome/napari-ome-zarr/issues/71 and https://github.com/ome/napari-ome-zarr/issues/21 for the upstream issues and https://ngff.openmicroscopy.org/0.4/index.html#bf2raw for the layout specification.

Until this is resolved in the napari plugin, you should be able to specify the specific image you want to open. In your example above, pointing at `/media/pablo/d7c61090-024c-469a-930c-f5ada47fb049/PabloVicenteMunuera/3D_SegmentedDB/results/WD1.1_17-03_WT_MP.zarr/0` should open the first image.

**Comment by Pablo1990** [comment]
Opening the '0' dir worked! Thanks for the tip! So I guess we will have to wait.

Thanks again!
Pablo

**Comment by sbesson** [comment]
Closing as the layout is expected and the reading issue should be handled at the plugin level
